config/routes.rb
Rails.application.routes.draw do
  
  as :customers do
    root to: 'customer#home', as: 'customer_root'
  end

  as :workers do
    root to: 'worker#home', as: 'worker_root'
  end

  devise_for :workers
  devise_for :customers
  
  root to: redirect('/home')

  get 'home', to: 'customer#home', as: 'home'
  get 'home/customer_profile', to: 'customer#customer_profile', as: 'customer_profile'
  
  get '/customer/customer_profile/my_jobs/', to: 'job#my_jobs', as: 'my_jobs'
  get '/customer/customer_profile/my_jobs/edit/:customer_id', to: 'job#edit', as: 'edit'
  patch '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update', as: 'update_job'
  put '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update'

  post '/customer/customer_profile/my_jobs/:job_id', to: 'reviews#create', as: 'create_review'
  get '/customer/customer_profile/my_jobs/:job_id/new_review', to: 'reviews#new', as: 'new_review'

  get '/home/jobs', to: 'job#jobs', as: 'jobs'
  
  post '/home/jobs', to: 'job#create'
  get '/home/jobs/new', to: 'job#new', as: 'new_job'

  get 'home/jobs/:specialty_index', to: 'job#index', as: 'job_type'
  
  delete '/home/jobs/:id', to: 'job#delete', as: 'delete_job'
  
  get 'home/worker', to: 'worker#home', as: 'worker_home'
  get 'home/worker/worker_profile', to: 'worker#worker_profile', as: 'worker_profile'
  
  get 'home/worker_directory/:specialty_index', to: 'worker#index', as: 'worker_directory'
  get 'home/worker_directory/:specialty_index/:id', to: 'worker#show', as: 'worker'

  get '/search', to: 'worker#search'
  get '/job_search', to: 'job#job_search'

  get 'home/worker_directory/:specialty_index/:id/worker_reviews', to: 'reviews#index', as: 'worker_reviews'
  get 'home/worker_directory/:specialty_index/:id/worker_reviews/:review_id', to: 'reviews#show', as: 'review'

  get 'home/worker_directory/:specialty_index/reviews/:review_value', to: 'worker#ratings_index', as: 'worker_directory_ratings'

end

app/models/worker.rb
# == Schema Information
#
# Table name: workers
#
#  id                     :bigint           not null, primary key
#  city                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  invisibility           :integer
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  specialty              :string
#  state                  :string
#  street_address         :string
#  zip_code               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_workers_on_email                 (email) UNIQUE
#  index_workers_on_reset_password_token  (reset_password_token) UNIQUE
#
class Worker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many(
    :jobs,
    class_name: 'Job',
    foreign_key: 'worker_id',
    inverse_of: :worker
  )

  has_many(
    :reviews, 
    through: :jobs
  )
  
  has_many(
    :messages,
    as: :sender
  )

  has_many(
    :messages,
    as: :receiver
  )

  def name
    first_name + " " + last_name
  end

  def average_rating
    result = 0.0

    reviews.each do |review|
      result = result + review.average_rating
    end
    return result/number_of_reviews
  end

  def number_of_reviews
    reviews.size()
  end
  
  def rating
    if(average_rating > 0.8)
      return 5
    elsif (average_rating > 0.6)
      return 4
    elsif (average_rating > 0.4)
      return 3
    elsif (average_rating > 0.2)
      return 2
    elsif (average_rating > 0.0)
      return 1
    else
      return 0
    end
  end
end

app/controllers/worker_controller.rb
class WorkerController < ApplicationController

    before_action :authenticate_worker!, except: [:home, :index, :show, :ratings_index, :search]
    before_action :require_permission, except: [:home, :index, :show, :ratings_index, :search]

    def require_permission
      if current_customer
        redirect_to home_path, flash: { error: "You do not have permission to do that." }
      end
    end

    def home
      if customer_signed_in?
        flash[:alert] = "You Must Sign Out First"
        redirect_back(fallback_location: root_path)
      else
        $SWITCH = 0
        render :worker_home
    
      end
    end
    
    def worker_profile
        render :worker_profile
    end

    def worker_jobs
      @not_started_jobs = current_worker.jobs.where("in_progress = ? AND completed = ?", false, false)
      @in_progress_jobs = current_worker.jobs.where("completed = ? AND in_progress = ?",false, true)
      @completed_jobs = current_worker.jobs.where("completed = ? AND in_progress = ?", true, false)

      if @not_started_jobs == nil
        @not_started_jobs = []
      end
      if @in_progress_jobs == nil
        @in_progress_jobs = []
      end
      if @completed_jobs == nil
        @completed_jobs = []
      end
        render :worker_jobs
    end

    def job_selection
      @job = Job.find(params[:job_id])
      @job.worker = current_worker
      if @job.save
        flash[:success] = "Job selected!"
        redirect_to worker_jobs_path
      else
        flash[:error] = "Job selection failed."
        redirect_to jobs_url
      end
    end

    def job_remove
      @job = Job.find(params[:job_id])
      @job.worker = Worker.find(1)
      if @job.save
        flash[:success] = "Job removed."
        redirect_to worker_jobs_path
      else
        flash[:error] = "Could not remove job from list"
        redirect_to worker_jobs_path
      end
    end

    def job_start
      @job = Job.find(params[:job_id])
      @job.in_progress = true
      if @job.save
        flash[:success] = "Job started."
        redirect_to worker_jobs_path
      else
        flash[:error] = "Could not start job."
        redirect_to worker_jobs_path
      end
      
    end

    def job_complete
      @job = Job.find(params[:job_id])
      @job.in_progress = false
      @job.save
      @job.completed = true
      if @job.save
        flash[:success] = "Job completed."
        redirect_to worker_jobs_path
      else
        flash[:error] = "Could not complete job"
        redirect_to worker_jobs_path
      end
    end


    def index
      # $SPECIALTY_TYPES is a global array populated with every specialty type available.
      # can be found in app/controllers/application_controller.rb
      
      # this is grabbing the extra data passed in the url and converting it to a integer
      @index = params[:specialty_index].to_i

      # -1 is the value passed when clicking the link to view all workers
      if params[:sort] == "first_name"
        @workers_to_display = Worker.where({invisibility: 0}).order(params[:sort]) 
      elsif params[:sort] == "last_name"
        @workers_to_display = Worker.where({invisibility: 0}).order(params[:sort])
      elsif @index != -1
        @workers_to_display = Worker.where({specialty: $SPECIALTY_TYPES.at(@index)})
      else
        @workers_to_display = Worker.where({invisibility: 0})
      end
      
      render :worker_directory
    end
    
    def show
        @worker = Worker.find(params[:id])
        render :worker
    end

    def search
        if params[:search].blank?
          redirect_to worker_directory_path(-1)
        else
          # @results returns searches done for first name or last name or the specialty
          # of the worker
          @parameter = params[:search].downcase
          @results = Worker.all.where("lower(first_name) LIKE :search", search: "%#{@parameter}%")
          @results += Worker.all.where("lower(last_name) LIKE :search", search: "%#{@parameter}%")
          @results += Worker.all.where("lower(specialty) LIKE :search", search: "%#{@parameter}%")
        end
    end

    def ratings_index
      @filter_value = params[:review_value].to_i
      @workers_to_display = []
      @index = 0
      
      Worker.all.each_with_index do |w|
        if w.rating == @filter_value
          @workers_to_display[@index] = w
          @index = @index + 1
        end
      end
      
      render :worker_directory
    end

end

app/helpers/worker_helper.rb
module WorkerHelper
end

app/views/worker/_no_workers_table_data.html.erb
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>
<td>N/A</td>

app/views/worker/search.erb
<h3> Search Results</h3>

<div class = "container p-3 my-3 bg-light text-black">
  <table class="table table-hover">

    <thead>
      <tr style="background-color:#7DAFE8;color:#ffffff;">
          <th>Name</th>
          <th>Specialty</th>
          <th>Rating</th>
          <th>Details</th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% if @results.size() == 0%>
        <%= render :partial => 'no_workers_table_data'%>
      <% else %>
        <% @results.each do |result|%>
          <% if result.invisibility == 0 %>
            <tr>
              <td><%= result.first_name %> <%= result.last_name %></td>
              <td><%= result.specialty %></td>
              <td>

                <%# this link takes the user to the worker reviews page%>

                <%= link_to worker_reviews_path(-1, result) do %>
                  <div style="inline-block;">

                    <%# @star is being assigned the value that is returned after calling the "stars" method in the worker model class %>
                    <%# and then @star is passed along to the partial "reviews/stars" %>
                    <% @rating = result.rating %>
                    <%= render :partial => 'reviews/rating', locals: { post: @rating } %>
                    <span>(<%= result.number_of_reviews%>)</span>
                  
                  </div>

                <% end %>
              </td>

              <td><%= link_to 'More Info', worker_path(-1, result) %></td>
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
    

  </table>
</div>

app/views/worker/worker.html.erb
<div class = "container p-3 my-3 bg-light">
<h1 class="text-center p-3">Details About <%= @worker.first_name %></h1>

  <table class="table text-center w-50 mx-auto">

    <thead class="thead-dark">
      <tr>
          <th>First Name</th>
          <th>Last Name</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @worker.first_name %> </td>
          <td><%= @worker.last_name %> </td>
        </tr>
    </tbody>

  </table>

  <table class="table text-center w-50 mx-auto">

    <thead class="thead-dark">
      <tr>
          <th>Email</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @worker.email %></td>
        </tr>
    </tbody>

  </table>

  <table class="table text-center w-50 mx-auto">

    <thead class="thead-dark">
      <tr>
          <th>Specialty</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= @worker.specialty %></td>
        </tr>
    </tbody>

  </table>

<% if @worker.reviews.size() != 0 %>
  <div class="card border border-secondary w-50 mx-auto">
    <div class="card-header bg-light" id="heading">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapse" aria-expanded="false" aria-controls="collapseOne" onclick="this.blur();">
          <p>Show Reviews</p>
        </button>
      </h5>
    </div>

    <div id="collapse" class="collapse bg-light" aria-labelledby="heading">
      <div class="card-body">
        <% @worker.reviews.each do |review|%>
          <div class="container p-3 mb-5 mt-5" style="border-bottom: 1px solid black;">
            <% @review = review%>
            <%= render :partial => 'reviews/review', locals: { review: @review } %>
            <p class="p-3"> Reviewed by <%= review.customer_name%> </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

<% else %>
    <h3 class= "text-center"> No Available Reviews </h3>
<% end %>

</div>

app/views/worker/worker_directory.html.erb
<style>
  a{
    text-decoration: none;
  }

  body{
    background-image: url(<%= asset_path 'assorted-tools.jpg' %>);
    background-position: bottom;
  }

  #page-container{
    padding: 10%;
  }

  /* Extra small devices (phones, 600px and down) */
  @media only screen and (max-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 400%;
    }
  }

  /* Small devices (portrait tablets and large phones, 600px and up) */
  @media only screen and (min-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 300%;
    }
  }

  /* Medium devices (landscape tablets, 768px and up) */
  @media only screen and (min-width: 768px) {
    body{
      background-repeat: no-repeat;
      background-size: 200%;
    }
  }

  /* Large devices (laptops/desktops, 992px and up) */
  @media only screen and (min-width: 992px) {
    body{
      background-repeat: no-repeat;
      background-size: 150%;
    }
  }

  /* Extra large devices (large laptops and desktops, 1200px and up) */
  @media only screen and (min-width: 1200px) {
    body{
      background-repeat: no-repeat;
      background-size: 100%;
    }

  }
</style>

<body>
<div class = "container p-3 my-3 text-dark" style="background: rgba(248, 249, 250, 0.8);">
<h1 class="text-center">Available Workers</h1>
  <div class="container text-light font-weight-bold">
    <a class="text-dark" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Filter
    </a>

    <div class="collapse" id="collapseExample">
      <li class="list-inline-item dropdown">
        <button type="button" class="btn dropdown-toggle text-dark font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="this.blur();">
          Type
        </button>

        <div class="dropdown-menu">
          <!-- loop way of displaying the menu -->
          <% $SPECIALTY_TYPES.each_with_index do |type, index|%>
            <p>
              <%= link_to $SPECIALTY_TYPES.at(index).to_s, worker_directory_path(index), class: 'dropdown-item'%>
            </p>
          <% end %>
          <%= link_to "See All", worker_directory_path(-1), class: 'dropdown-item'%>
        </div>
      </li>
    
      <li class="list-inline-item dropdown">
        <button type="button" class="btn dropdown-toggle text-dark font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sort By
        </button>
        <div class="dropdown-menu">
          <%= link_to "First Name", worker_directory_path(:sort => "first_name"), class: 'dropdown-item'%>
          <%= link_to "Last Name", worker_directory_path(:sort => "last_name"), class: 'dropdown-item'%>
        </div>
      </li>

      <li class="list-inline-item dropdown">
        <button type="button" class="btn dropdown-toggle text-dark font-weight-bold" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          By Review
        </button>
        <div class="dropdown-menu">
          <%= link_to "1-Star Rating", worker_directory_ratings_path(-1,1), class: 'dropdown-item'%>
          <%= link_to "2-Star Ratings", worker_directory_ratings_path(-1,2), class: 'dropdown-item'%>
          <%= link_to "3-Star Ratings", worker_directory_ratings_path(-1,3), class: 'dropdown-item'%>
          <%= link_to "4-Star Ratings", worker_directory_ratings_path(-1,4), class: 'dropdown-item'%>
          <%= link_to "5-Star Ratings", worker_directory_ratings_path(-1,5), class: 'dropdown-item'%>
        </div>
      </li>
    </div>
  </div>

  <table class="table text-dark font-weight-bolder" style="overflow-y:auto;">

    <thead>
      <tr class="light-blue"style="background-color:#7DAFE8;color:#ffffff;">
          <th>Name</th>
          <th>Specialty</th>
          <th>Rating</th>
          <th>Details</th>
          <th></th>
      </tr>
    </thead>

    <%# tbody is used to display the worker information in a table body%>
    <%# if there are no workers to display, render a partial with the table data for no workers%>
    <tbody>
      <% if @workers_to_display.size() == 0%>
        <%= render :partial => 'no_workers_table_data'%>
      <% else %>
        <% @workers_to_display.each do |w| %>
          <tr>
            <td><%= w.name %></td>
            <td><%= w.specialty%></td>
            <td>

              <%# this link takes the user to the worker reviews page%>
              <%= link_to worker_reviews_path(@index, w) do %>
                <div class="text-dark"style="inline-block;">

                  <%# @star is being assigned the value that is returned after calling the "stars" method in the worker model class %>
                  <%# and then @star is passed along to the partial "reviews/stars" %>
                  <% @rating = w.rating %>
                  <%= render :partial => 'reviews/rating', locals: { post: @rating } %>
                  <span>(<%= w.number_of_reviews%>)</span>
                
                </div>
              
              <% end %>
            </td>
            <td><%= link_to 'More Info', worker_path(@index, w), class: "text-dark" %></td>
          </tr>
        <% end %> 
      <% end %>
    </tbody>

  </table>
</div>

</body>

app/views/worker/worker_home.html.erb
<style>
  body{
    background-image: url(<%= asset_path 'colorful-tools.jpeg' %>);
  }

  #page-container{
    padding: 10%;
  }
 
  /* <%# Extra small devices (phones, 600px and down) %>
  @media only screen and (max-width: 600px) {
    body{
      background-repeat: repeat;
      background-size: 400%;
    }
  }

  <%# Small devices (portrait tablets and large phones, 600px and up)%>
  @media only screen and (min-width: 600px) {
    body{
      background-repeat: repeat;
      background-size: 300%;
    }
  }

  <%#Medium devices (landscape tablets, 768px and up) %>
  @media only screen and (min-width: 768px) {
    body{
      background-repeat: repeat;
      background-size: 200%;
    }
  }

  <%#Large devices (laptops/desktops, 992px and up) %>  
  @media only screen and (min-width: 992px) {
    body{
      background-repeat: repeat;
      background-size: 150%;
    }
  }

  /* <%# Extra large devices (large laptops and desktops, 1200px and up)%>
  @media only screen and (min-width: 1200px) {
    body{
      background-repeat: repeat;
      background-size: 100%;
    }

  } */
</style>

<div class="container-fluid text-light text-center" id="page-container" style="background: rgba(0, 0, 0, 0.5);">
  <h1 class="display-1"><strong>HOME</strong></h1>

  <% if worker_signed_in?%>
    <p class="container h4 p-2">Hi, <%= current_worker.first_name %></p>
  <% end %>

  <div class="btn-group-vertical btn-group-lg">
    <% if worker_signed_in? %>
      <%= link_to 'My Profile', worker_profile_path, class: 'btn btn-dark-red'%>
      <%= link_to 'Job Board', jobs_path, class: 'btn btn-dark-red'%>
      <%= link_to 'Sign Out', destroy_worker_session_path, method: :delete, class: 'btn btn-dark-red' %>
    <% else %>
      <%= link_to 'Job Board', jobs_path, class: 'btn btn-dark-red'%>
    <% end %>
  </div>
</div>

app/views/worker/worker_jobs.html.erb
<style>
  img{
    display: inline-block;
    width: 10pt;
    height: 10pt;
    padding: 0px 1px;
  }
 .hidden{
    display: none;
  }

  .rating{
    display: block;
  }

  body{
    background-image: url(<%= asset_path 'worker-jobs-pic.jpg' %>);
  }

  #page-container{
    padding: 5%;
  }

  /* Extra small devices (phones, 600px and down) */
  @media only screen and (max-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 400%;
    }
  }

  /* Small devices (portrait tablets and large phones, 600px and up) */
  @media only screen and (min-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 300%;
    }
  }

  /* Medium devices (landscape tablets, 768px and up) */
  @media only screen and (min-width: 768px) {
    body{
      background-repeat: no-repeat;
      background-size: 200%;
    }
  }

  /* Large devices (laptops/desktops, 992px and up) */
  @media only screen and (min-width: 992px) {
    body{
      background-repeat: no-repeat;
      background-size: 150%;
    }
  }

  /* Extra large devices (large laptops and desktops, 1200px and up) */
  @media only screen and (min-width: 1200px) {
    body{
      background-repeat: no-repeat;
      background-size: 100%;
    }

  }
</style>

<body>
<div class="container-fluid" id='page-container' style="background: rgba(0, 0, 0, 0.5);">
        <p class="text-light text-center h1">
            Hi, <%= current_worker.first_name %>
        </p>
    <div class="container p-2 text-center text-light h3">Here are your jobs</div>


  <div class="btn-group container-fluid p-3 my-3 text-black">
    <button id="not-completed" type="button" class="btn btn-cyan active">To-Do</button>
    <button id="in-progress" type="button" class="btn btn-cyan">In-Progress</button>
    <button id="completed" type="button" class="btn btn-cyan">Completed</button>
  </div>

  <div id="posts not-completed"> 
    
    <div class="container p-3">
        <%= link_to "Select A Job", jobs_path, class: 'btn btn-dark-red'%>
    </div>
    
    <% if @not_started_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_selected_message'%>
      </div>
    <% else %>
      <% @not_started_jobs.each do |job| %>
      
        <% if job.worker_id == current_worker.id and job.completed == false and job.in_progress == false%>
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job/job', locals: { job: @job } %>

            <%= link_to "Remove From To-Do list", job_remove_path(job), class: "btn btn-dark-red" %>
            <%= link_to "Start Job", job_start_path(job), class: "btn btn-dark-red" %>

          </div>
        
        <% end %>
      <% end %>
    <% end %>

  </div>

  <div id="posts in-progress" class="hidden">

    <% if @in_progress_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_in_progress_message'%>
      </div>
    <% else %>
      <% @in_progress_jobs.each do |job| %>
        <% if job.worker_id == current_worker.id and job.in_progress == true%>
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job/job', locals: { job: @job } %>
          
            <%= link_to 'Move to Completed', job_complete_path(job), class: 'btn btn-dark-red'%>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div id="posts completed" class="hidden">
    <% if @completed_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_completed_message'%>
      </div>
    <% else %>
      <% @completed_jobs.each_with_index do |job, index| %>

        <% @review = job.reviews%>

        <% if job.worker_id == current_worker.id and job.completed == true%>
          <% if job.reviews != nil%>
            <% ratings = [job.reviews.reliability_rating, job.reviews.honesty_rating, job.reviews.skill_rating, job.reviews.focused_rating]%>
          <% end %>
          
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job/job', locals: { job: @job } %>

            <p>Completed By <%= link_to job.worker_name, worker_path(1, job.worker_id) %></p>

            <% if job.reviews == nil%>
              <div class="container p-3 bg-light">
                <p>Customer has not reviewed your work yet. Come back later.</p>
              </div>
            <% else %>
              
              <div class="card border-dark">
                <div class="card-header" id="heading<%=index.to_s%>">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse<%=index.to_s%>" aria-expanded="false" aria-controls="collapseOne" onclick="this.blur();">
                      <% @rating = @review.average_rating %>
                      Average rating for <%= job.worker_name%>
                      <%= render :partial => 'reviews/rating', locals: { post: @rating } %>
                    </button>
                  </h5>
                </div>

                <div id="collapse<%=index.to_s%>" class="collapse bg-light" aria-labelledby="heading<%=index.to_s%>">
                  <div class="card-body">
                    <%= render :partial => 'reviews/review', locals: { review: @review } %>
                  </div>
                </div>
              </div>

            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

<script>
  var btn1 = document.getElementById('completed');
  var btn2 = document.getElementById('not-completed');
  var btn3 = document.getElementById('in-progress');

  btn1.addEventListener("click", onClick);
  btn2.addEventListener("click", onClick);
  btn3.addEventListener("click", onClick);

  function onClick(event){
    let className = event.target.className;
    let id = event.target.id;

    if(id == "completed"){
      document.getElementById("posts not-completed").className = "hidden"
      document.getElementById("posts in-progress").className = "hidden"
      event.target.className = "btn btn-cyan active"
      document.getElementById("not-completed").className = "btn btn-cyan"
      document.getElementById("in-progress").className = "btn btn-cyan"
      document.getElementById("posts completed").className = ""
    }
    else if(id == "in-progress"){
      document.getElementById("posts not-completed").className = "hidden"
      document.getElementById("posts completed").className = "hidden"
      event.target.className = "btn btn-cyan active"
      document.getElementById("not-completed").className = "btn btn-cyan"
      document.getElementById("completed").className = "btn btn-cyan"
      document.getElementById("posts in-progress").className = ""
    }
    else{
      document.getElementById("posts in-progress").className = "hidden"
      document.getElementById("posts completed").className = "hidden"
      event.target.className = "btn btn-cyan active"
      document.getElementById("in-progress").className = "btn btn-cyan"
      document.getElementById("completed").className = "btn btn-cyan"
      document.getElementById("posts not-completed").className = ""
    }
  }

</script>

</div>
</body>

app/views/worker/worker_profile.html.erb
<style>

.table{
    width: 50%;
    margin: auto;
    font-family: Georgia, Garamond
}

</style>

<div class = "container p-3 my-3 bg-light text-black">
    <h1 class="text-center"><%= current_worker.first_name %>'s Profile</h1>

    <div class="btn-group-vertical" style="margin-left:82%;width:10%;">
        <%= link_to 'Edit Profile', edit_worker_registration_path, class: 'btn btn-dark-red' %>
        <%= link_to 'My Jobs', worker_jobs_path, class: 'btn btn-dark-red' %>
    </div>

    <table class="table text-center w-50 bg-cyan">
        <thead class="thead-dark">
            <tr>
                <th>Name</th>
                <th>Email Address</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= current_worker.name %></td>
                <td><%= current_worker.email %></td>
            </tr>
        </tbody>
    </table>

    <table class="table text-center w-50 bg-cyan">
        <thead class="thead-dark">
            <tr>
            <th>Street Address</th>
            </tr>
        </thead>

        <tbody>
            <tr>
            <td><%= current_worker.street_address %></td>
            </tr>
            <thead class="thead-dark">
                <tr>
                <th>City/State</th>
                </tr>
            </thead>
            <tr>
            <td><%= current_worker.city %>, <%= current_worker.state %></td>
            </tr>
            <thead class="thead-dark">
                <tr>
                <th>Zip Code</th>
                </tr>
            </thead>
            <tr>
            <td><%= current_worker.zip_code %></td>
            </tr>
        </tbody>
    </table>

    <table class="table text-center w-50 bg-cyan">
        <thead class="thead-dark">
        <tr>
        <th>Specialty</th>
        </tr>
    </thead>

        <tbody>
            <tr>
            <td><%= current_worker.specialty %></td>
            </tr>
        </tbody>
    </table>