config/routes.rb
Rails.application.routes.draw do
  
  as :customers do
    root to: 'customer#home', as: 'customer_root'
  end

  as :workers do
    root to: 'worker#home', as: 'worker_root'
  end

  devise_for :workers
  devise_for :customers
  
  root to: redirect('/home')

  get 'home', to: 'customer#home', as: 'home'
  get 'home/customer_profile', to: 'customer#customer_profile', as: 'customer_profile'
  
  get '/customer/customer_profile/my_jobs/', to: 'job#my_jobs', as: 'my_jobs'
  get '/customer/customer_profile/my_jobs/edit/:customer_id', to: 'job#edit', as: 'edit'
  patch '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update', as: 'update_job'
  put '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update'

  post '/customer/customer_profile/my_jobs/:job_id', to: 'reviews#create', as: 'create_review'
  get '/customer/customer_profile/my_jobs/:job_id/new_review', to: 'reviews#new', as: 'new_review'

  get '/home/jobs', to: 'job#jobs', as: 'jobs'
  
  post '/home/jobs', to: 'job#create'
  get '/home/jobs/new', to: 'job#new', as: 'new_job'

  get 'home/jobs/:specialty_index', to: 'job#index', as: 'job_type'
  
  delete '/home/jobs/:id', to: 'job#delete', as: 'delete_job'
  
  get 'home/worker', to: 'worker#home', as: 'worker_home'
  get 'home/worker/worker_profile', to: 'worker#worker_profile', as: 'worker_profile'
  
  get 'home/worker_directory/:specialty_index', to: 'worker#index', as: 'worker_directory'
  get 'home/worker_directory/:specialty_index/:id', to: 'worker#show', as: 'worker'

  get '/search', to: 'worker#search'
  get '/job_search', to: 'job#job_search'

  get 'home/worker_directory/:specialty_index/:id/worker_reviews', to: 'reviews#index', as: 'worker_reviews'
  get 'home/worker_directory/:specialty_index/:id/worker_reviews/:review_id', to: 'reviews#show', as: 'review'

  get 'home/worker_directory/:specialty_index/reviews/:review_value', to: 'worker#ratings_index', as: 'worker_directory_ratings'

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :bigint           not null, primary key
#  completed   :boolean
#  description :string
#  in_progress :boolean
#  name        :string
#  specialty   :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  customer_id :bigint
#  worker_id   :bigint
#
# Indexes
#
#  index_jobs_on_customer_id  (customer_id)
#  index_jobs_on_worker_id    (worker_id)
#
# Foreign Keys
#
#  fk_rails_...  (customer_id => customers.id)
#  fk_rails_...  (worker_id => workers.id)
#
class Job < ApplicationRecord
    belongs_to(
        :customer,
        class_name: 'Customer',
        foreign_key: 'customer_id',
        inverse_of: :jobs
      )

      has_one(
        :reviews,
        class_name: 'Review',
        foreign_key: 'job_id',
        inverse_of: :job,
        dependent: :destroy
      )

      belongs_to(
        :worker,
        class_name: 'Worker',
        foreign_key: 'worker_id',
        inverse_of: :jobs
      )

      def customer_name
        customer.name
      end

      def worker_name
        worker.name
      end

      def worker_id
        worker.id
      end

      def customer_email
        customer.email
      end

      def customer_first_name
        customer.first_name
      end

      def average_rating
        if reviews == nil
          return 0.0
        else
          reviews.average_rating
        end
      end
end

app/controllers/job_controller.rb
class JobController < ApplicationController

  def jobs
    @jobs = Job.where("completed = ? AND in_progress = ?", false, false)
    render :jobs
  end

  def index
    # $SPECIALTY_TYPES is a global array populated with every specialty type available.
    # can be found in app/controllers/application_controller.rb
    
    # this is grabbing the extra data passed in the url and converting it to a integer
    @index = params[:specialty_index].to_i

    # -1 is the value passed when clicking the link to view all workers
    if @index != -1
      @jobs = Job.where("specialty = ? AND completed = ? AND in_progress = ?", $SPECIALTY_TYPES.at(@index), false, false)
    else
      @jobs = Job.where("completed = ? AND in_progress = ?", false, false)
    end
    
    render :jobs
  end

  def new
    @customer = Customer.find(current_customer.id)
    @job = Job.new
    $SPECIALTY_TYPES.prepend("select")
    render :new
  end

  def create
    @customer = Customer.find(current_customer.id)
    @job = @customer.jobs.build(params.require(:job).permit(:name, :description, :specialty))
    @job.completed = false
    @job.in_progress = false
    @job.worker = Worker.find(1)
    if @job.save
      flash[:success] = "New Job Posting added!"
      redirect_to jobs_url
    else
      flash.now[:error] = "Job failed to post"
      render :new
    end
    $SPECIALTY_TYPES.delete_at(0)
  end

  def delete
    @job = Job.find(params[:id])
    @job.destroy
    flash[:success] = "The job has been successfully destroyed."
    redirect_to jobs_path

  end  


  def my_jobs
    @not_selected_jobs = current_customer.jobs.where("worker_id = ?", 1)
    @in_progress_jobs = current_customer.jobs.where("completed = ? AND in_progress = ?",false, true)
    @completed_jobs = current_customer.jobs.where("completed = ? AND in_progress = ?", true, false)
    render :my_jobs
  end

  def edit
    @job = current_customer.jobs.find(params[:customer_id])
    render :edit
  end

  def update
    @job = current_customer.jobs.find(params[:customer_id])
    if @job.update(params.require(:job).permit(:name, :description, :specialty))
      flash[:success] = "Job updated successfully"
      redirect_to my_jobs_path
    else
      flash.now[:error] = "Job could not be updated"
      render :edit

    end
  end


  def job_search
    if params[:job_search].blank?
      redirect_to jobs_path(-1)
    else
      @parameter = params[:job_search].downcase
      @jobs = Job.all.where("lower(specialty) LIKE :search", search: "%#{@parameter}%")
    end
  end
  
end

app/helpers/job_helper.rb
module JobHelper
end

app/views/job/_job.html.erb
  <h2><%= @job.name %></h2>
  <p>Posted By <strong><%= @job.customer.first_name%></strong> </p>
  <p><%= @job.specialty %></p>
  <p><%= @job.description %></p>

app/views/job/_no_jobs_completed_message.html.erb
<% if current_customer %>
  <p>
    You have no completed jobs at this time.
  </p>
<% else%>
  <p>
    You have not completed any jobs yet.
  </p>
<% end %>

app/views/job/_no_jobs_in_progress_message.html.erb
<% if current_customer %>
  <p>
    You have no jobs in progress at this time.
  </p>
<% else%>
  <p>
    You aren't working on any jobs. Start one!
  </p>
<% end %>

app/views/job/_no_jobs_message.html.erb
<% if current_customer %>
  <p>
    There are no job posts at this time. Add one now?
  </p>
<% else%>
  <p>
    There are no job posts at this time. Come back later.
  </p>
<% end %>

app/views/job/_no_jobs_selected_message.html.erb
  <p>
    You don't have any job listings selected at this time. Select one!
  </p>

app/views/job/edit.html.erb
<h1>Edit your Job Request</h1>

<%= bootstrap_form_with model: @job, url: update_job_path(@job), method: :patch, local: true do |job| %>
  
  <%= job.text_field :name, label: 'Job Title'%>
  <%= job.text_area :description %>
  <%= job.select :specialty, $SPECIALTY_TYPES, label: 'Specialty Preference' %>
  <%= job.submit 'Update Posting', class: 'btn btn-custom-color' %>

<% end %>

<p class="mt-3">
  <%= link_to 'Cancel', my_jobs_path(@job), class: 'btn btn-custom-color' %>
</p>

app/views/job/job_search.erb
<h1 class="header-center">Job results</h1>

<div class="posts">
  <% @jobs.each_with_index do |job, index| %>
    <div class="posting">
      <a data-toggle="collapse" href="#collapseExample<%= index %>" role="button" aria-expanded="false" aria-controls="collapseExample">
        <%= job.name %>
      </a>

      <div class="collapse" id="collapseExample<%= index %>">
        <div class="card card-body">
          <h3><%= job.customer.first_name%></h3>
          <p><%= job.specialty %></p>
          <p><%= job.description %></p>
          <p>For more information, contact <span style="font-weight:bold"><%= job.customer.first_name%></span> at:
            <li><%= job.customer.email%></li>
          </p>
        </div>
      </div>
    </div>

<% end %>

app/views/job/jobs.html.erb
<h1 class="header-center">Job Board</h1>
<div class="container-fluid">
  <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Filter
  </a>
  <div class="collapse" id="collapseExample">
    <li class="list-inline-item dbtn-group dropright">
      <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Type
      </button>
      <div class="dropdown-menu">
        <!-- loop way of displaying the menu -->
        <% $SPECIALTY_TYPES.each_with_index do |type, index|%>
          <p>
            <%= link_to $SPECIALTY_TYPES.at(index).to_s, job_type_path(index), class: 'dropdown-item'%>
          </p>
        <% end %>
        <%= link_to "See All", job_type_path(-1), class: 'dropdown-item'%>
      </div>
    </li>
  </div>
</div>

<div style="margin-top:20px;">
  <% if customer_signed_in? && $SWITCH == 1%>
    <p>
      <%= link_to "Add A Job Posting", new_job_path, class: 'btn btn-custom-color'%>
    </p>
  <% end %>
</div>


<div class="posts">
  <% if @jobs.size() == 0 %>
    <div class="container-fluid p-3 my-3 bg-light text-black">
      <%= render :partial => 'no_jobs_message'%>
    </div>
  <% else %>
    <% @jobs.each do |job| %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <% @job = job %>
        <%= render :partial => 'job', locals: { job: @job } %>
        
        <p>For more information, contact <span style="font-weight:bold"><%= job.customer.first_name%></span> at:
          <li><%= job.customer.email%></li>
        </p>
        <%# The Delete button allows users to remove a posted job from the job board.
        This happens because delete_job_path takes the job id and calles the destroy 
        function in the job_controller.
        %>
        <%# The button will show only when a customer is signed in and they have a job posted.%>
        <% if customer_signed_in?%>
          <% if job.customer_id == current_customer.id%>
            <td><%= link_to "Delete", delete_job_path(job), method: :delete, class: "btn btn-custom-color" %></td>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% end %>
  
</div>




app/views/job/my_jobs.html.erb
<style>
  img{
    display: inline-block;
    width: 10pt;
    height: 10pt;
    padding: 0px 1px;
  }
 .hidden{
    display: none;
  }

  .rating{
    display: block;
  }

</style>


<h1 class="header-center">My Jobs</h1>

<body>
  <div class="btn-group container-fluid p-3 my-3 text-black">
    <button id="not-completed" type="button" class="btn btn-primary active">not started</button>
    <button id="in-progress" type="button" class="btn btn-primary">in-progress</button>
    <button id="completed" type="button" class="btn btn-primary">completed</button>
  </div>

  <div id="posts not-completed"> 
    
    <div style="margin-top:20px;">
      <p>
        <%= link_to "Add A Job Posting", new_job_path, class: 'btn btn-custom-color'%>
      </p>
    </div>
    
    <% if @not_selected_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'no_jobs_message'%>
      </div>
    <% else %>
      <% @not_selected_jobs.each do |job| %>
      
        <% if job.customer_id == current_customer.id and job.completed == false and job.in_progress == false%>
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job', locals: { job: @job } %>

            <td><%= link_to "Delete", delete_job_path(job), method: :delete, class: "btn btn-custom-color" %></td>

          </div>
        
        <% end %>
      <% end %>
    <% end %>

  </div>

  <div id="posts in-progress" class="hidden">

    <% if @in_progress_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'no_jobs_in_progress_message'%>
      </div>
    <% else %>
      <% @in_progress_jobs.each do |job| %>
        <% if job.customer_id == current_customer.id and job.in_progress == true%>
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job', locals: { job: @job } %>
          
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div id="posts completed" class="hidden">
    <% if @completed_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'no_jobs_completed_message'%>
      </div>
    <% else %>
      <% @completed_jobs.each_with_index do |job, index| %>

        <% @review = job.reviews%>

        <% if job.customer_id == current_customer.id and job.completed == true%>
          <% if job.reviews != nil%>
            <% ratings = [job.reviews.reliability_rating, job.reviews.honesty_rating, job.reviews.skill_rating, job.reviews.focused_rating]%>
          <% end %>
          
          <div class="container-fluid p-3 my-3 bg-light text-black">

            <% @job = job %>
            <%= render :partial => 'job', locals: { job: @job } %>

            <p>Completed By <%= link_to job.worker_name, worker_path(1, job.worker_id) %></p>

            <% if job.reviews == nil%>
              <div class="btn-group container-fluid p-3 my-3 text-black w-25">
                <%= link_to 'add a review', new_review_path(job), class: "btn btn-custom-color" %>
              </div>
            <% else %>
              
              <div class="card border-dark">
                <div class="card-header" id="heading<%=index.to_s%>">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse<%=index.to_s%>" aria-expanded="false" aria-controls="collapseOne" onclick="this.blur();">
                      <% @rating =@review.rating %>
                      Average rating for <%= job.worker_name%>
                      <%= render :partial => 'reviews/rating', locals: { post: @rating } %>
                    </button>
                  </h5>
                </div>

                <div id="collapse<%=index.to_s%>" class="collapse bg-light" aria-labelledby="heading<%=index.to_s%>">
                  <div class="card-body">
                    <%= render :partial => 'reviews/review', locals: { review: @review } %>
                  </div>
                </div>
              </div>

            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

<script>
  var btn1 = document.getElementById('completed');
  var btn2 = document.getElementById('not-completed');
  var btn3 = document.getElementById('in-progress');

  btn1.addEventListener("click", onClick);
  btn2.addEventListener("click", onClick);
  btn3.addEventListener("click", onClick);

  function onClick(event){
    let className = event.target.className;
    let id = event.target.id;

    if(id == "completed"){
      document.getElementById("posts not-completed").className = "hidden"
      document.getElementById("posts in-progress").className = "hidden"
      event.target.className = "btn btn-primary active"
      document.getElementById("not-completed").className = "btn btn-primary"
      document.getElementById("in-progress").className = "btn btn-primary"
      document.getElementById("posts completed").className = ""
    }
    else if(id == "in-progress"){
      document.getElementById("posts not-completed").className = "hidden"
      document.getElementById("posts completed").className = "hidden"
      event.target.className = "btn btn-primary active"
      document.getElementById("not-completed").className = "btn btn-primary"
      document.getElementById("completed").className = "btn btn-primary"
      document.getElementById("posts in-progress").className = ""
    }
    else{
      document.getElementById("posts in-progress").className = "hidden"
      document.getElementById("posts completed").className = "hidden"
      event.target.className = "btn btn-primary active"
      document.getElementById("in-progress").className = "btn btn-primary"
      document.getElementById("completed").className = "btn btn-primary"
      document.getElementById("posts not-completed").className = ""
    }
  }

</script>

</body>

app/views/job/new.html.erb
<h1>Post a Job Request</h1>

<%= bootstrap_form_with model: @job, url: jobs_path, method: :post, local: true do |job| %>
  <%= job.text_field :name, label: 'Title'%>
  <%= job.text_area :description %>
  <%= job.select :specialty, $SPECIALTY_TYPES.prepend("select"), label: 'Specialty Preference' %>
  <%= job.submit 'Submit Posting', class: 'btn btn-custom-color' %>

<% end %>

 <%$SPECIALTY_TYPES.delete_at(0)%>