config/routes.rb
Rails.application.routes.draw do
  
  as :customers do
    root to: 'customer#home', as: 'customer_root'
  end

  as :workers do
    root to: 'worker#home', as: 'worker_root'
  end

  devise_for :workers
  devise_for :customers
  
  root to: redirect('/home')

  get 'home', to: 'customer#home', as: 'home'
  get 'home/customer_profile', to: 'customer#customer_profile', as: 'customer_profile'
  
  get '/customer/customer_profile/my_jobs/', to: 'job#my_jobs', as: 'my_jobs'
  get '/customer/customer_profile/my_jobs/edit/:customer_id', to: 'job#edit', as: 'edit'
  patch '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update', as: 'update_job'
  put '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update'

  post '/customer/customer_profile/my_jobs/:job_id', to: 'reviews#create', as: 'create_review'
  get '/customer/customer_profile/my_jobs/:job_id/new_review', to: 'reviews#new', as: 'new_review'

  get '/home/jobs', to: 'job#jobs', as: 'jobs'
  
  post '/home/jobs', to: 'job#create'
  get '/home/jobs/new', to: 'job#new', as: 'new_job'

  get 'home/jobs/:specialty_index', to: 'job#index', as: 'job_type'
  
  delete '/home/jobs/:id', to: 'job#delete', as: 'delete_job'
  
  get 'home/worker', to: 'worker#home', as: 'worker_home'
  get 'home/worker/worker_profile', to: 'worker#worker_profile', as: 'worker_profile'
  
  get 'home/worker_directory/:specialty_index', to: 'worker#index', as: 'worker_directory'
  get 'home/worker_directory/:specialty_index/:id', to: 'worker#show', as: 'worker'

  get '/search', to: 'worker#search'
  get '/job_search', to: 'job#job_search'

  get 'home/worker_directory/:specialty_index/:id/worker_reviews', to: 'reviews#index', as: 'worker_reviews'
  get 'home/worker_directory/:specialty_index/:id/worker_reviews/:review_id', to: 'reviews#show', as: 'review'

  get 'home/worker_directory/:specialty_index/reviews/:review_value', to: 'worker#ratings_index', as: 'worker_directory_ratings'

end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id                     :bigint           not null, primary key
#  city                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  state                  :string
#  street_address         :string
#  zip_code               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_customers_on_email                 (email) UNIQUE
#  index_customers_on_reset_password_token  (reset_password_token) UNIQUE
#
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many(
    :jobs,
    class_name: 'Job',
    foreign_key: 'customer_id',
    inverse_of: :customer,
    dependent: :destroy
  )

  has_many(
    :messages,
    as: :sender
  )

  has_many(
    :messages,
    as: :receiver
  )

  def name
    first_name + " " + last_name
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
    before_action :authenticate_customer!, except: [:home]

    def home
        if worker_signed_in?
          flash[:alert] = "You Must Sign Out First"
          redirect_back(fallback_location: root_path)
        else
          $SWITCH = 1
          render :home
        end
    end

    def customer_profile
        render :customer_profile
    end

    def my_jobs
        @not_started_jobs = current_customer.jobs.where("completed = ? AND in_progress = ?", false, false)
        @in_progress_jobs = current_customer.jobs.where("completed = ? AND in_progress = ?",false, true)
        @completed_jobs = current_customer.jobs.where("completed = ? AND in_progress = ?", true, false)

        render :my_jobs
    end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/customer_profile.html.erb
<style>
.table{
    width: 50%;
    margin: auto;
    font-family: Georgia, Garamond
}
</style>

<h1 class="text-center"><%= current_customer.first_name %>'s Profile</h1>

<div class = "container p-3 my-3 bg-light text-black">
    
    <div class="btn-group-vertical btn-group-sm" style="margin-left:82%;width:10%;">
        <%= link_to 'My Jobs',my_jobs_path(), class: 'btn btn-primary' %>
        <%= link_to 'Edit Profile',edit_customer_registration_path(current_customer), class: 'btn btn-primary' %>
  </div>

    <table class="table text-center">
        <thead>
            <tr style="background-color:#7DAFE8;color:#ffffff;">
                <th>Name</th>
                <th>Email Address</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= current_customer.first_name %> <%= current_customer.last_name %></td>
                <td><%= current_customer.email %></td>
            </tr>
        </tbody>
    </table>

    <table class="table text-center">
        <thead>
            <tr style="background-color:#7DAFE8;color:#ffffff;">
                <th>Street Address</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><%= current_customer.street_address %></td>
            </tr>
            <thead>
                <tr style="background-color:#7DAFE8;color:#ffffff;">
                <th>City/State</th>
                </tr>
            </thead>
            <tr>
                <td><%= current_customer.city %>, <%= current_customer.state %></td>
            </tr>
            <thead>
                <tr style="background-color:#7DAFE8;color:#ffffff;">
                <th>Zip Code</th>
                </tr>
            </thead>
            <tr>
                <td><%= current_customer.zip_code %></td>
            </tr>
        </tbody>
    </table><br>
</div>

app/views/customer/home.html.erb

<style>

  body{
    background-image: url(<%= asset_path 'home.jpg' %>);
  }

  #page-container{
    padding: 10%;
  }

  /* Extra small devices (phones, 600px and down) */
  @media only screen and (max-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 400%;
    }
  }

  /* Small devices (portrait tablets and large phones, 600px and up) */
  @media only screen and (min-width: 600px) {
    body{
      background-repeat: no-repeat;
      background-size: 300%;
    }
  }

  /* Medium devices (landscape tablets, 768px and up) */
  @media only screen and (min-width: 768px) {
    body{
      background-repeat: no-repeat;
      background-size: 200%;
    }
  }

  /* Large devices (laptops/desktops, 992px and up) */
  @media only screen and (min-width: 992px) {
    body{
      background-repeat: no-repeat;
      background-size: 150%;
    }
  }

  /* Extra large devices (large laptops and desktops, 1200px and up) */
  @media only screen and (min-width: 1200px) {
    body{
      background-repeat: no-repeat;
      background-size: 100%;
    }

  }
</style>

<body>
  
<div class="container-fluid text-light text-center" id='page-container' style="background: rgba(0, 0, 0, 0.5);">

  <h1 class="display-1"><strong>HOME</strong></h1>

  <% if customer_signed_in?%>
    <p class="container h4 p-2">Hi, <%= current_customer.first_name %></p>
  <% end %>

  <div class="btn-group-vertical btn-group-lg">
    <% if customer_signed_in? %>
      <%= link_to 'My Profile', customer_profile_path, class: 'btn btn-custom-color'%>   
      <%= link_to 'Job Board', jobs_path, class: 'btn btn-custom-color'%>   
      <%= link_to 'Sign Out', destroy_customer_session_path, method: :delete, class: 'btn btn-custom-color' %>
    <% else %>
        <%= link_to 'Job Board', jobs_path, class: 'btn btn-custom-color'%>
    <% end %>
  </div>

</div>
</body>



app/views/customer/my_jobs.html.erb
<style>
  #star{
    display: inline-block;
    width: 15pt;
    height: 15pt;
    padding: 0px 1px;
  }
  img{
    width: 200px;
    height: 200px;
  }
 .hidden{
    display: none;
  }

  .rating{
    display: block;
  }

  body{
    background-image: url(<%= asset_path 'vintage-wood.jpg' %>);
  }

  /* Extra small devices (phones, 600px and down) */
  @media only screen and (max-width: 600px) {
    body{
      background-repeat: repeat;
      background-size: 400%;
    }
  }

  /* Small devices (portrait tablets and large phones, 600px and up) */
  @media only screen and (min-width: 600px) {
    body{
      background-repeat: repeat;
      background-size: 300%;
    }
  }

  /* Medium devices (landscape tablets, 768px and up) */
  @media only screen and (min-width: 768px) {
    body{
      background-repeat: repeat;
      background-size: 200%;
    }
  }

  /* Large devices (laptops/desktops, 992px and up) */
  @media only screen and (min-width: 992px) {
    body{
      background-repeat: repeat;
      background-size: 150%;
    }
  }

  /* Extra large devices (large laptops and desktops, 1200px and up) */
  @media only screen and (min-width: 1200px) {
    body{
      background-repeat: no-repeat;
      background-size: 150%;
    }
  }


</style>

<body>
<div class="container-fluid p-5" style="background: rgba(0, 0, 0, 0.5);">
  <h1 class="header-center text-light">Hi, <%= current_customer.first_name%> </h1>
  <p class="container p-2 text-center text-light h3">Here are your job listings</p>

  <div class="btn-group container-fluid p-3 my-3 text-black">
    <button id="not-completed" type="button" class="btn btn-light-blue active">not started</button>
    <button id="in-progress" type="button" class="btn btn-light-blue">in-progress</button>
    <button id="completed" type="button" class="btn btn-light-blue">completed</button>
  </div>

  <div id="posts not-completed"> 
    
    <div style="margin-top:20px;">
      <p>
        <%= link_to "Add A Job Posting", new_job_path, class: 'btn btn-custom-color'%>
      </p>
    </div>
    
    <% if @not_started_jobs.size() == 0 %>

      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_message'%>
      </div>
      
    <% else %>
      <% @not_started_jobs.each do |job| %>
        <% if job.customer_id == current_customer.id and job.completed == false and job.in_progress == false%>

          <div class="container-fluid p-3 my-3 bg-light text-black">
            <% @job = job %>
            <%= render :partial => 'job/job', locals: { job: @job } %>
            <div class="btn-group-vertical">
              <%= link_to "Edit", edit_path(job), class: 'btn btn-custom-color'%>
              <%= link_to "Delete", delete_job_path(job), method: :delete, class: "btn btn-light-red" %>
            </div>
          </div>

        <% end %>
      <% end %>
    <% end %>

  </div>

  <div id="posts in-progress" class="hidden">

    <% if @in_progress_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_in_progress_message'%>
      </div>

    <% else %>
      <% @in_progress_jobs.each do |job| %>
        <% if job.customer_id == current_customer.id and job.in_progress == true%>

          <div class="container-fluid p-3 my-3 bg-light text-black">
            <% @job = job %>
            <%= render :partial => 'job/job', locals: { job: @job } %>
          </div>

        <% end %>
      <% end %>
    <% end %>
  </div>

  <div id="posts completed" class="hidden">
    <% if @completed_jobs.size() == 0 %>
      <div class="container-fluid p-3 my-3 bg-light text-black">
        <%= render :partial => 'job/no_jobs_completed_message'%>
      </div>

    <% else %>
      <% @completed_jobs.each_with_index do |job, index| %>
        <% @review = job.reviews%>
        <% if job.customer_id == current_customer.id and job.completed == true%>
          <% if job.reviews != nil%>
            <% ratings = [job.reviews.reliability_rating, job.reviews.honesty_rating, job.reviews.skill_rating, job.reviews.focused_rating]%>
          <% end %>
          <div class="container-fluid p-3 my-3 bg-light text-black">
            <% @job = job %>
            
            <%= render :partial => 'job/job', locals: { job: @job } %>

            <p>Completed By <%= link_to job.worker_name, worker_path(1, job.worker_id) %></p>
            <% if job.reviews == nil%>
              <div class="btn-group container-fluid p-3 my-3 text-black w-25">
                <%= link_to 'add a review', new_review_path(job), class: "btn btn-custom-color" %>
              </div>
            <% else %>
              <div class="card border-secondary">
                <div class="card-header bg-light" id="heading<%=index.to_s%>">
                  <h5 class="mb-0">
                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse<%=index.to_s%>" aria-expanded="false" aria-controls="collapseOne" onclick="this.blur();">
                      <% @rating = @review.average_rating %>
                      <%= render :partial => 'reviews/rating', locals: { post: @rating } %>
                      <span style="font-size:10pt;">(See Details of <%= @review.worker_first_name%>'s Performance)</span>
                    </button>
                  </h5>
                </div>

                <div id="collapse<%=index.to_s%>" class="collapse bg-light" aria-labelledby="heading<%=index.to_s%>">
                  <div class="card-body">
                    <%= render :partial => 'reviews/review', locals: { review: @review } %>
                  </div>
                </div>
              </div>

            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <script>
    var btn1 = document.getElementById('completed');
    var btn2 = document.getElementById('not-completed');
    var btn3 = document.getElementById('in-progress');

    btn1.addEventListener("click", onClick);
    btn2.addEventListener("click", onClick);
    btn3.addEventListener("click", onClick);

    function onClick(event){
      let className = event.target.className;
      let id = event.target.id;

      if(id == "completed"){
        document.getElementById("posts not-completed").className = "hidden"
        document.getElementById("posts in-progress").className = "hidden"
        event.target.className = "btn btn-light-blue active"
        document.getElementById("not-completed").className = "btn btn-light-blue"
        document.getElementById("in-progress").className = "btn btn-light-blue"
        document.getElementById("posts completed").className = ""
      }
      else if(id == "in-progress"){
        document.getElementById("posts not-completed").className = "hidden"
        document.getElementById("posts completed").className = "hidden"
        event.target.className = "btn btn-light-blue active"
        document.getElementById("not-completed").className = "btn btn-light-blue"
        document.getElementById("completed").className = "btn btn-light-blue"
        document.getElementById("posts in-progress").className = ""
      }
      else{
        document.getElementById("posts in-progress").className = "hidden"
        document.getElementById("posts completed").className = "hidden"
        event.target.className = "btn btn-light-blue active"
        document.getElementById("in-progress").className = "btn btn-light-blue"
        document.getElementById("completed").className = "btn btn-light-blue"
        document.getElementById("posts not-completed").className = ""
      }
    }

  </script>
</div>
</body>

app/views/customer/workerhome.html.erb
<h1>Worker home page<h1>

    <ul class="navbar-nav">
      <% if worker_signed_in? %>
        <li class="nav-item">
          <%= link_to "Hi, #{current_worker.email}", edit_worker_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_worker_session_path, method: :delete, class: 'nav-link' 'btn btn-primary' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_worker_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_worker_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>

<p>
  <%= link_to 'Logo', home_path %>
</p>