config/routes.rb
Rails.application.routes.draw do
  
  as :customers do
    root to: 'customer#home', as: 'customer_root'
  end

  as :workers do
    root to: 'worker#home', as: 'worker_root'
  end

  devise_for :workers
  devise_for :customers
  
  root to: redirect('/home')

  get 'home', to: 'customer#home', as: 'home'
  get 'home/customer_profile', to: 'customer#customer_profile', as: 'customer_profile'
  
  get '/customer/customer_profile/my_jobs/', to: 'job#my_jobs', as: 'my_jobs'
  get '/customer/customer_profile/my_jobs/edit/:customer_id', to: 'job#edit', as: 'edit'
  patch '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update', as: 'update_job'
  put '/customer/customer_profile/my_jobs/:customer_id', to: 'job#update'

  post '/customer/customer_profile/my_jobs/:job_id', to: 'reviews#create', as: 'create_review'
  get '/customer/customer_profile/my_jobs/:job_id/new_review', to: 'reviews#new', as: 'new_review'

  get '/home/jobs', to: 'job#jobs', as: 'jobs'
  
  post '/home/jobs', to: 'job#create'
  get '/home/jobs/new', to: 'job#new', as: 'new_job'

  get 'home/jobs/:specialty_index', to: 'job#index', as: 'job_type'
  
  delete '/home/jobs/:id', to: 'job#delete', as: 'delete_job'
  
  get 'home/worker', to: 'worker#home', as: 'worker_home'
  get 'home/worker/worker_profile', to: 'worker#worker_profile', as: 'worker_profile'
  
  get 'home/worker_directory/:specialty_index', to: 'worker#index', as: 'worker_directory'
  get 'home/worker_directory/:specialty_index/:id', to: 'worker#show', as: 'worker'

  get '/search', to: 'worker#search'
  get '/job_search', to: 'job#job_search'

  get 'home/worker_directory/:specialty_index/:id/worker_reviews', to: 'reviews#index', as: 'worker_reviews'
  get 'home/worker_directory/:specialty_index/:id/worker_reviews/:review_id', to: 'reviews#show', as: 'review'

  get 'home/worker_directory/:specialty_index/reviews/:review_value', to: 'worker#ratings_index', as: 'worker_directory_ratings'

end

app/views/layouts/_customer_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-light-brown">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Handyman', home_path, class: 'navbar-brand', style: 'color:black'%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Services
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

          <!-- loop way of displaying the menu -->
          <% $SPECIALTY_TYPES.each_with_index do |type, index|%>
            <p>
              <%= link_to $SPECIALTY_TYPES.at(index).to_s, worker_directory_path(index), class: 'dropdown-item'%>
            </p>
          <% end %>
          <%= link_to "See All", worker_directory_path(-1), class: 'dropdown-item'%>
        </div>
      </li>
      

      <li class="nav-item">
        <%= link_to 'Find a Handyman', worker_directory_path(-1), class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Are you a Handyman?', worker_home_path, class: 'nav-link' %>
      </li>

      <% if customer_signed_in? %>
        <li class="nav-item ml-auto">
          <%= link_to "Hi, #{current_customer.first_name}", nil, class: 'nav-link' %>
        </li>

        <li>
          <%= link_to 'My Profile', customer_profile_path,  class: 'nav-link'%>
        </li>

        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_customer_session_path, method: :delete, class: 'nav-link' %>
        </li>
        
        <li class="nav-item ">
          <%= form_tag(search_path, :method => "get") do %>
            <div class="input-group">
              <%= search_field_tag :search, params[:search], placeholder: "Find a worker", class: "form-control" %>
              <div class="input-group-btn">
                <%= button_tag "Search", :class => 'btn btn-primary', :name => nil%>
              </div>
            </div>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_customer_session_path, class: 'nav-link' %>
        </li>

        <li class="nav-item" style="float:right">
          <%= link_to 'Sign Up', new_customer_registration_path, class: 'nav-link' %>
        </li>
        
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_worker_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-sm bg-light-red">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Handyman', worker_home_path, class: 'navbar-brand', style: 'color:black'%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          find a Job
        </a>
        
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <!-- loop way of displaying the menu -->
          <% $SPECIALTY_TYPES.each_with_index do |type, index|%>
            <p>
              <%= link_to $SPECIALTY_TYPES.at(index).to_s, job_type_path(index), class: 'dropdown-item'%>
            </p>
          <% end %>
          <%= link_to "See All", job_type_path(-1), class: 'dropdown-item'%>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to 'Are you a Customer?', home_path, class: 'nav-link'%>
      </li>

      <% if worker_signed_in? %>
        <li class="nav-item">
          <%= link_to "Hi, #{current_worker.first_name}", worker_profile_path, class: 'nav-link' %>
        </li>

        <li>
          <%= link_to 'My Profile', worker_profile_path, class: 'nav-link'%>
        </li>

        <li class="nav-item">
          <%= button_to 'Sign Out', destroy_worker_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_worker_session_path, class: 'nav-link'%>
        </li>
        
        <li class="nav-item" style="float:right">
          <%= link_to 'Sign Up', new_worker_registration_path, class: 'nav-link'%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneHandyman</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <main role="main" class="container">
    <% flash.each do |key, message| %>
      <div class="alert <%= flash_class(key) %> alert-dismissible fade show text-center" role="alert">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    
    <% if $SWITCH == 1%>
      <%= render :partial => 'layouts/customer_navbar'%>
    <% else %>
      <%= render :partial => 'layouts/worker_navbar'%>
    <% end %>
  <%= yield %>
  </main>
</html>